apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: prestadoresacr12345.azurecr.io/prestadores-back:v3
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://prestadores-postgres-demo.postgres.database.azure.com:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: pgadmin
            - name: SPRING_DATASOURCE_PASSWORD
              value: DemoPassword123!